
changelog:
  categories:
    - title: ':newspaper: [target: A](https://github.com/tsuna-can-se/temp)'
      labels:
        - 'target: A'
      exclude:
        labels:
          - dependencies
    - title: ':newspaper: [target: B](https://github.com/tsuna-can-se/temp)'
      labels:
        - 'target: B'
      exclude:
        labels:
          - dependencies
    - title: ':label: dependencies'
      labels:
        - dependencies
