
changelog:
  categories:
    - title: ':newspaper: [features](https://github.com/tsuna-can-se/temp)'
      labels:
        - 'enhancement'
      exclude:
        labels:
          - dependencies
    - title: ':label: dependencies'
      labels:
        - dependencies
