
changelog:
  categories:
    - title: ':newspaper: features'
      labels:
        - 'feature'
      exclude:
        labels:
          - dependencies
    - title: ':label: dependencies'
      labels:
        - dependencies
